apiVersion: apps.openliberty.io/v1beta2
kind: OpenLibertyApplication
metadata:
  name: inventory-deployment
  labels:
    name: inventory-deployment
spec:
  applicationImage: liberty-deepdive-inventory:1.0-SNAPSHOT
  service:
    port: 9443
  env:
    - name: POSTGRES_HOSTNAME
      value: "postgres"

